/**
 * Deine tägliche Nährstoff- & Supplement-Übersicht
 */

export const MY_SUPPLEMENTS = [
  {
    id: 'watson-male-essentials',
    name: 'Male Essentials',
    brand: 'Watson Nutrition',
    dosage: '1 Kapsel täglich',
    timing: 'Morgens zum Frühstück',
    icon: '☀️',
    badge: '21 Nährstoffe',
    image: 'assets/images/watson-male-essentials.png',
    url: 'https://watsonnutrition.de/products/male-essentials'
  },
  {
    id: 'watson-collasyn',
    name: 'CollaSyn®',
    brand: 'Watson Nutrition',
    dosage: '1 Stick täglich (4,3 g Pulver)',
    timing: 'Morgens / Im Shake',
    icon: '✨',
    badge: '4.000 mg Glycin + Hyaluron',
    image: 'assets/images/watson-collasyn.png',
    url: 'https://watsonnutrition.de/products/collasyn'
  },
  {
    id: 'vitamoment-d3-k2',
    name: 'Vitamin D3 + K2',
    brand: 'VitaMoment',
    dosage: '1 Kapsel täglich',
    timing: 'Morgens mit Fettquelle',
    icon: '☀️',
    badge: '5.000 IE D3 + 200 µg K2',
    image: 'assets/images/vitamoment-d3-k2.png',
    url: 'https://vitamoment.de/products/vitamin-d3-k2'
  },
  {
    id: 'vitamoment-vitamin-c',
    name: 'Vitamin C (gepuffert)',
    brand: 'VitaMoment',
    dosage: '1 Kapsel täglich',
    timing: 'Morgens / Mittags',
    icon: '🍊',
    badge: '500 mg Vitamin C',
    image: 'assets/images/vitamoment-vitamin-c.png',
    url: 'https://vitamoment.de/products/vitamin-c'
  },
  {
    id: 'zinzino-balanceoil',
    name: 'BalanceOil+ (Omega-3)',
    brand: 'Zinzino',
    dosage: '10 ml täglich (flüssig)',
    timing: 'Morgens / Mittags zum Essen',
    icon: '🐟',
    badge: '2.065 mg Omega-3',
    image: 'assets/images/zinzino-balanceoil.png',
    url: 'https://www.zinzino.com/shop/site/at/de-de/products/shop/omega-supplements/300000'
  },
  {
    id: 'true-nature-cholin',
    name: 'Cholin Bitartrat',
    brand: 'True Nature',
    dosage: '3 Kapseln täglich (1.125 mg)',
    timing: 'Morgens / Mittags',
    icon: '🧠',
    badge: '450 mg Cholin',
    image: 'assets/images/true-nature-cholin.png',
    url: ''
  },
  {
    id: 'sports-health-magnesium',
    name: 'Magnesium Bisglycinat',
    brand: 'Sports & Health',
    dosage: '3 Kapseln täglich',
    timing: 'Abends vor dem Schlafen',
    icon: '🌙',
    badge: '400 mg Magnesium',
    image: 'assets/images/sports-health-magnesium.png',
    url: ''
  },
  {
    id: 'gloryfeel-creatine',
    name: 'Kreatin Creapure®',
    brand: 'Gloryfeel',
    dosage: '1 Messlöffel täglich (3,4 g)',
    timing: 'Morgens / Nach dem Training',
    icon: '⚡',
    badge: '3.000 mg Creapure®',
    image: 'assets/images/gloryfeel-creatine.png',
    url: 'https://www.amazon.de/dp/B0CX9FJNMM'
  }
];

export const NUTRIENTS_SUMMARY = [
  // --- VITAMINE ---
  {
    category: 'vitamins',
    categoryName: 'Vitamine',
    name: 'Vitamin D3',
    extra: '7.667 IE (125 µg VitaMoment + 50 µg Watson + 16,7 µg Zinzino)',
    amount: '191.7 µg',
    rawAmount: 191.7,
    unit: 'µg',
    ref: '20 µg (D-A-CH)',
    percent: 958,
    source: 'VitaMoment + Watson + Zinzino',
    sourceBrand: 'VitaMoment + Watson + Zinzino',
    isVeganCritical: true,
    supplementIds: ['watson-male-essentials', 'vitamoment-d3-k2', 'zinzino-balanceoil']
  },
  {
    category: 'vitamins',
    categoryName: 'Vitamine',
    name: 'Vitamin K2',
    extra: '200 µg VitaMoment + 70 µg Watson (MK-7 all-trans)',
    amount: '270 µg',
    rawAmount: 270,
    unit: 'µg',
    ref: '70 µg (D-A-CH)',
    percent: 386,
    source: 'VitaMoment + Watson',
    sourceBrand: 'VitaMoment + Watson',
    supplementIds: ['watson-male-essentials', 'vitamoment-d3-k2']
  },
  {
    category: 'vitamins',
    categoryName: 'Vitamine',
    name: 'Vitamin C',
    extra: '580 mg (500 mg VitaMoment + 80 mg Watson CollaSyn)',
    amount: '580 mg',
    rawAmount: 580,
    unit: 'mg',
    ref: '110 mg (D-A-CH)',
    percent: 527,
    source: 'VitaMoment + Watson CollaSyn',
    sourceBrand: 'VitaMoment + Watson',
    supplementIds: ['vitamoment-vitamin-c', 'watson-collasyn']
  },
  {
    category: 'vitamins',
    categoryName: 'Vitamine',
    name: 'Vitamin B12',
    extra: 'Methyl- & Adenosylcobalamin',
    amount: '50 µg',
    rawAmount: 50,
    unit: 'µg',
    ref: '4.0 µg (D-A-CH)',
    percent: 1250,
    source: 'Watson Male Essentials',
    sourceBrand: 'Watson Nutrition',
    isVeganCritical: true,
    supplementIds: ['watson-male-essentials']
  },
  {
    category: 'vitamins',
    categoryName: 'Vitamine',
    name: 'Vitamin A',
    extra: 'Retinylacetat',
    amount: '600 µg',
    rawAmount: 600,
    unit: 'µg',
    ref: '850 µg (D-A-CH)',
    percent: 71,
    source: 'Watson Male Essentials',
    sourceBrand: 'Watson Nutrition',
    supplementIds: ['watson-male-essentials']
  },
  {
    category: 'vitamins',
    categoryName: 'Vitamine',
    name: 'Vitamin E',
    extra: 'D-alpha-Tocopherol',
    amount: '14 mg',
    rawAmount: 14,
    unit: 'mg',
    ref: '14 mg (D-A-CH)',
    percent: 100,
    source: 'Watson Male Essentials',
    sourceBrand: 'Watson Nutrition',
    supplementIds: ['watson-male-essentials']
  },
  {
    category: 'vitamins',
    categoryName: 'Vitamine',
    name: 'Vitamin B1',
    extra: 'Thiamin HCL',
    amount: '1.6 mg',
    rawAmount: 1.6,
    unit: 'mg',
    ref: '1.2 mg (D-A-CH)',
    percent: 133,
    source: 'Watson Male Essentials',
    sourceBrand: 'Watson Nutrition',
    supplementIds: ['watson-male-essentials']
  },
  {
    category: 'vitamins',
    categoryName: 'Vitamine',
    name: 'Vitamin B2',
    extra: 'Riboflavin-5-Phosphat (aktiv)',
    amount: '1.6 mg',
    rawAmount: 1.6,
    unit: 'mg',
    ref: '1.4 mg (D-A-CH)',
    percent: 114,
    source: 'Watson Male Essentials',
    sourceBrand: 'Watson Nutrition',
    supplementIds: ['watson-male-essentials']
  },
  {
    category: 'vitamins',
    categoryName: 'Vitamine',
    name: 'Vitamin B3 (Niacin)',
    extra: 'Nicotinamid',
    amount: '15 mg',
    rawAmount: 15,
    unit: 'mg',
    ref: '16 mg (D-A-CH)',
    percent: 94,
    source: 'Watson Male Essentials',
    sourceBrand: 'Watson Nutrition',
    supplementIds: ['watson-male-essentials']
  },
  {
    category: 'vitamins',
    categoryName: 'Vitamine',
    name: 'Vitamin B5 (Pantothensäure)',
    extra: 'Calcium-D-Pantothenat',
    amount: '5.0 mg',
    rawAmount: 5.0,
    unit: 'mg',
    ref: '6.0 mg (D-A-CH)',
    percent: 83,
    source: 'Watson Male Essentials',
    sourceBrand: 'Watson Nutrition',
    supplementIds: ['watson-male-essentials']
  },
  {
    category: 'vitamins',
    categoryName: 'Vitamine',
    name: 'Vitamin B6',
    extra: 'Pyridoxal-5-Phosphat (aktiv)',
    amount: '1.6 mg',
    rawAmount: 1.6,
    unit: 'mg',
    ref: '1.6 mg (D-A-CH)',
    percent: 100,
    source: 'Watson Male Essentials',
    sourceBrand: 'Watson Nutrition',
    supplementIds: ['watson-male-essentials']
  },
  {
    category: 'vitamins',
    categoryName: 'Vitamine',
    name: 'Vitamin B7 (Biotin)',
    extra: 'D-Biotin',
    amount: '40 µg',
    rawAmount: 40,
    unit: 'µg',
    ref: '40 µg (D-A-CH)',
    percent: 100,
    source: 'Watson Male Essentials',
    sourceBrand: 'Watson Nutrition',
    supplementIds: ['watson-male-essentials']
  },
  {
    category: 'vitamins',
    categoryName: 'Vitamine',
    name: 'Vitamin B9 (Folat)',
    extra: 'Quatrefolic® (5-MTHF)',
    amount: '200 µg',
    rawAmount: 200,
    unit: 'µg',
    ref: '300 µg (D-A-CH)',
    percent: 67,
    source: 'Watson Male Essentials',
    sourceBrand: 'Watson Nutrition',
    supplementIds: ['watson-male-essentials']
  },

  // --- MINERALSTOFFE & SPURENELEMENTE ---
  {
    category: 'minerals',
    categoryName: 'Mineralstoffe & Spurenelemente',
    name: 'Magnesium',
    extra: 'Magnesium-Bisglycinat (Chelat)',
    amount: '400 mg',
    rawAmount: 400,
    unit: 'mg',
    ref: '350 mg (D-A-CH)',
    percent: 114,
    source: 'Sports & Health Magnesium',
    sourceBrand: 'Sports & Health',
    supplementIds: ['sports-health-magnesium']
  },
  {
    category: 'minerals',
    categoryName: 'Mineralstoffe & Spurenelemente',
    name: 'Zink',
    extra: 'Zink-Bisglycinat',
    amount: '10 mg',
    rawAmount: 10,
    unit: 'mg',
    ref: '14 mg (D-A-CH)',
    percent: 71,
    source: 'Watson Male Essentials',
    sourceBrand: 'Watson Nutrition',
    isVeganCritical: true,
    supplementIds: ['watson-male-essentials']
  },
  {
    category: 'minerals',
    categoryName: 'Mineralstoffe & Spurenelemente',
    name: 'Eisen',
    extra: 'Ferrochel® Eisen-Bisglycinat',
    amount: '6.0 mg',
    rawAmount: 6.0,
    unit: 'mg',
    ref: '10 mg (D-A-CH)',
    percent: 60,
    source: 'Watson Male Essentials',
    sourceBrand: 'Watson Nutrition',
    isVeganCritical: true,
    supplementIds: ['watson-male-essentials']
  },
  {
    category: 'minerals',
    categoryName: 'Mineralstoffe & Spurenelemente',
    name: 'Selen',
    extra: 'Selenmethionin & Natriumselenit',
    amount: '70 µg',
    rawAmount: 70,
    unit: 'µg',
    ref: '70 µg (D-A-CH)',
    percent: 100,
    source: 'Watson Male Essentials',
    sourceBrand: 'Watson Nutrition',
    isVeganCritical: true,
    supplementIds: ['watson-male-essentials']
  },
  {
    category: 'minerals',
    categoryName: 'Mineralstoffe & Spurenelemente',
    name: 'Jod',
    extra: 'Kaliumjodid',
    amount: '150 µg',
    rawAmount: 150,
    unit: 'µg',
    ref: '200 µg (D-A-CH)',
    percent: 75,
    source: 'Watson Male Essentials',
    sourceBrand: 'Watson Nutrition',
    isVeganCritical: true,
    supplementIds: ['watson-male-essentials']
  },
  {
    category: 'minerals',
    categoryName: 'Mineralstoffe & Spurenelemente',
    name: 'Calcium',
    extra: 'Calcium-Bisglycinat',
    amount: '120 mg',
    rawAmount: 120,
    unit: 'mg',
    ref: '1.000 mg (D-A-CH)',
    percent: 12,
    source: 'Watson Male Essentials',
    sourceBrand: 'Watson Nutrition',
    supplementIds: ['watson-male-essentials']
  },
  {
    category: 'minerals',
    categoryName: 'Mineralstoffe & Spurenelemente',
    name: 'Kupfer',
    extra: 'Kupfer-Bisglycinat',
    amount: '0.5 mg',
    rawAmount: 0.5,
    unit: 'mg',
    ref: '1.0 mg (D-A-CH)',
    percent: 50,
    source: 'Watson Male Essentials',
    sourceBrand: 'Watson Nutrition',
    supplementIds: ['watson-male-essentials']
  },
  {
    category: 'minerals',
    categoryName: 'Mineralstoffe & Spurenelemente',
    name: 'Mangan',
    extra: 'Mangan-Bisglycinat',
    amount: '1.0 mg',
    rawAmount: 1.0,
    unit: 'mg',
    ref: '2.0 mg (D-A-CH)',
    percent: 50,
    source: 'Watson Male Essentials',
    sourceBrand: 'Watson Nutrition',
    supplementIds: ['watson-male-essentials']
  },
  {
    category: 'minerals',
    categoryName: 'Mineralstoffe & Spurenelemente',
    name: 'Chrom',
    extra: 'Chrompicolinat',
    amount: '20 µg',
    rawAmount: 20,
    unit: 'µg',
    ref: '30 µg (D-A-CH)',
    percent: 67,
    source: 'Watson Male Essentials',
    sourceBrand: 'Watson Nutrition',
    supplementIds: ['watson-male-essentials']
  },
  {
    category: 'minerals',
    categoryName: 'Mineralstoffe & Spurenelemente',
    name: 'Molybdän',
    extra: 'Natriummolybdat',
    amount: '25 µg',
    rawAmount: 25,
    unit: 'µg',
    ref: '50 µg (D-A-CH)',
    percent: 50,
    source: 'Watson Male Essentials',
    sourceBrand: 'Watson Nutrition',
    supplementIds: ['watson-male-essentials']
  },

  // --- SPEZIAL, OMEGA-3 & PERFORMANCE ---
  {
    category: 'special',
    categoryName: 'Performance & Nicht-Fleischesser',
    name: 'Omega-3 (EPA & DHA)',
    extra: '1.069 mg EPA + 569 mg DHA + 427 mg DPA (Wildfischöl)',
    amount: '2.065 mg',
    rawAmount: 2065,
    unit: 'mg',
    ref: '250 mg (EFSA Mindestbedarf)',
    percent: 826,
    source: 'Zinzino BalanceOil+',
    sourceBrand: 'Zinzino',
    isVeganCritical: true,
    supplementIds: ['zinzino-balanceoil']
  },
  {
    category: 'special',
    categoryName: 'Performance & Nicht-Fleischesser',
    name: 'Glycin (Kollagen-Aminosäure)',
    extra: '4.000 mg Diamond® Markenrohstoff – Primäre Aminosäure für Kollagenaufbau',
    amount: '4.000 mg',
    rawAmount: 4000,
    unit: 'mg',
    ref: '3.000 mg (Optimale Tagesdosis)',
    percent: 133,
    source: 'Watson CollaSyn®',
    sourceBrand: 'Watson Nutrition',
    isVeganCritical: true,
    supplementIds: ['watson-collasyn']
  },
  {
    category: 'special',
    categoryName: 'Performance & Nicht-Fleischesser',
    name: 'Hyaluronsäure',
    extra: '200 mg HAPLEX®Plus Natriumhyaluronat für Hautelastizität & Gelenke',
    amount: '200 mg',
    rawAmount: 200,
    unit: 'mg',
    ref: '100 mg (Studien-Referenzwert)',
    percent: 200,
    source: 'Watson CollaSyn®',
    sourceBrand: 'Watson Nutrition',
    supplementIds: ['watson-collasyn']
  },
  {
    category: 'special',
    categoryName: 'Performance & Nicht-Fleischesser',
    name: 'Kreatin (Creapure®)',
    extra: '100% mikronisiertes Creapure® (Alzchem Deutschland)',
    amount: '3.000 mg',
    rawAmount: 3000,
    unit: 'mg',
    ref: '3.000 mg (EFSA Wirksamkeit)',
    percent: 100,
    source: 'Gloryfeel Creapure®',
    sourceBrand: 'Gloryfeel',
    isVeganCritical: true,
    supplementIds: ['gloryfeel-creatine']
  },
  {
    category: 'special',
    categoryName: 'Performance & Nicht-Fleischesser',
    name: 'Cholin',
    extra: 'Reines Cholin (aus 1.125 mg Cholinbitartrat)',
    amount: '450 mg',
    rawAmount: 450,
    unit: 'mg',
    ref: '400 mg (EFSA AI)',
    percent: 113,
    source: 'True Nature Cholin',
    sourceBrand: 'True Nature',
    isVeganCritical: true,
    supplementIds: ['true-nature-cholin']
  },
  {
    category: 'special',
    categoryName: 'Performance & Nicht-Fleischesser',
    name: 'L-Carnitin',
    extra: 'Kommt fast nur in Fleisch vor – transportiert langkettige Fettsäuren in Mitochondrien',
    amount: '0 mg',
    rawAmount: 0,
    unit: 'mg',
    ref: '500 mg (Bedarfsempfehlung)',
    percent: 0,
    source: 'Nicht im aktuellen Stack',
    sourceBrand: 'Offen / 0 mg',
    isVeganCritical: true,
    supplementIds: []
  },
  {
    category: 'special',
    categoryName: 'Performance & Nicht-Fleischesser',
    name: 'Taurin',
    extra: 'Nur in tierischem Gewebe – zelluläre Osmoregulation, Gallensäuren & Herzschutz',
    amount: '0 mg',
    rawAmount: 0,
    unit: 'mg',
    ref: '500 mg (Bedarfsempfehlung)',
    percent: 0,
    source: 'Nicht im aktuellen Stack',
    sourceBrand: 'Offen / 0 mg',
    isVeganCritical: true,
    supplementIds: []
  },
  {
    category: 'special',
    categoryName: 'Performance & Nicht-Fleischesser',
    name: 'Carnosin / Beta-Alanin',
    extra: 'Carnosin kommt nur in Fleisch vor – intrazellulärer Säurepuffer im Muskel & Gehirn',
    amount: '0 mg',
    rawAmount: 0,
    unit: 'mg',
    ref: '1.500 mg (Bedarfsempfehlung)',
    percent: 0,
    source: 'Nicht im aktuellen Stack',
    sourceBrand: 'Offen / 0 mg',
    isVeganCritical: true,
    supplementIds: []
  },
  {
    category: 'special',
    categoryName: 'Performance & Nicht-Fleischesser',
    name: 'Oliven-Polyphenole',
    extra: 'Aus vorzeitig geerntetem nativem Olivenöl extra (Antioxidans)',
    amount: '2.9 mg',
    rawAmount: 2.9,
    unit: 'mg',
    ref: '5.0 mg (EFSA Health Claim)',
    percent: 58,
    source: 'Zinzino BalanceOil+',
    sourceBrand: 'Zinzino',
    supplementIds: ['zinzino-balanceoil']
  }
];
