/**
 * Wissenschaftliche Detail-Datenbank für alle 50 Nährstoffe
 * Fundierte biochemische Wirkmechanismen, D-A-CH / DGE / EFSA Referenzwerte,
 * spezifische Einordnung für fleisch- und fischfreie Ernährung sowie Einnahme-Synergien.
 */

export const NUTRIENT_DETAILS = {
  // =========================================================================
  // VITAMINE (13)
  // =========================================================================
  'vit-a': {
    id: 'vit-a',
    name: 'Vitamin A',
    scientificName: 'Retinol / Retinylacetat',
    categoryName: 'Vitamine',
    badge: '☀️ Fettlösliches Vitamin',
    summary: 'Essenziell für Sehkraft, Immunabwehr, Genexpression und Zellerneuerung von Haut und Schleimhäuten.',
    biochemistry: 'Vitamin A dient als Retinal im Sehpigment Rhodopsin der Netzhaut für das Hell-Dunkel-Sehen. In Form von Retinsäure bindet es an nukleäre RAR/RXR-Rezeptoren und moduliert die Transkription von über 500 Genen, die Zellproliferation, Epithelregeneration und T-Zell-Differenzierung steuern.',
    plantBasedRelevance: 'Pflanzliche Nahrung liefert nur Provitamin A (Beta-Carotin), dessen enzymatische Spaltung durch BCMO1 genetisch stark variiert (bis zu 45% der Bevölkerung sind schlechte Konvertierer). Vorgeformtes Retinol im Stack sichert die zelluläre Versorgung unabhängig von genetischen Konversions-Engpässen direkt ab.',
    intakeAdvice: 'Fettlöslich: Immer zu einer Mahlzeit mit Fettquelle einnehmen. Zink ist als Kofaktor für das Transportprotein (Retinol-bindendes Protein, RBP) zwingend erforderlich.',
    safetyAndUL: 'EFSA Tolerable Upper Limit (UL): 3.000 µg/Tag. Die Zufuhr von 600 µg (71% DGE / D-A-CH für Männer) ist ideal balanciert und vermeidet jegliche Akkumulation in der Leber.',
    scientificReference: 'EFSA Journal 2015;13(3):4028 | D-A-CH Referenzwerte 2020'
  },
  'vit-d3': {
    id: 'vit-d3',
    name: 'Vitamin D3',
    scientificName: 'Cholecalciferol (7.667 IE / 191,7 µg)',
    categoryName: 'Vitamine',
    badge: '☀️ Steroidhormon-Präkursor',
    summary: 'Schlüsselhormon für Knochendichte, Calcium-Homöostase, Muskelleistung und angeborene sowie adaptive Immunfunktion.',
    biochemistry: 'Cholecalciferol wird in der Leber zu 25(OH)D und in den Nieren/Zellen zum aktiven Steroidhormon Calcitriol (1,25(OH)2D) hydroxyliert. Calcitriol bindet an den Vitamin-D-Rezeptor (VDR) in fast allen Geweben und reguliert über 1.000 Gene, u.a. antimikrobielle Peptide (Cathelicidin) und Calcium-Transportproteine.',
    plantBasedRelevance: 'Bei Verzicht auf fetten Seefisch (Lachs, Hering, Makrele) existiert in pflanzlichen Lebensmitteln praktisch keine nennenswerte Vitamin-D-Quelle. In mitteleuropäischen Breitengraden reicht die UV-B-Strahlung von Oktober bis April physikalisch nicht für eine Eigensynthese aus – Supplementierung ist obligatorisch.',
    intakeAdvice: 'Morgens oder mittags mit Fettquelle einnehmen. Zwingend synergistisch mit Vitamin K2 (Aktivierung von Osteocalcin & Matrix-Gla-Protein) und Magnesium (Kofaktor für die Hydroxylasen) kombinieren.',
    safetyAndUL: 'EFSA Upper Limit für die Allgemeinbevölkerung: 4.000 IE (100 µg)/Tag. In Kombination mit hoher K2-Gabe (270 µg) und Magnesium wird das Risiko einer Weichteilkalzifizierung physiologisch minimiert.',
    scientificReference: 'EFSA Journal 2012;10(7):2813 | D-A-CH Referenzwerte | Endocrine Society Clinical Guidelines'
  },
  'vit-e': {
    id: 'vit-e',
    name: 'Vitamin E',
    scientificName: 'D-Alpha-Tocopherol',
    categoryName: 'Vitamine',
    badge: '🛡️ Fettlösliches Antioxidans',
    summary: 'Primäres fettlösliches Antioxidans zum Schutz von Zellmembranen und mehrfach ungesättigten Fettsäuren vor Lipidperoxidation.',
    biochemistry: 'Alpha-Tocopherol fängt freie Radikale (Peroxylradikale) in Lipiddoppelschichten ab, bevor diese ungesättigte Fettsäuren in Membranen oxidieren können. Das dabei entstehende Tocopheroxyl-Radikal wird im zellulären Redoxnetzwerk primär durch Vitamin C wieder in seine aktive Form regeneriert.',
    plantBasedRelevance: 'Bei hoher Zufuhr mehrfach ungesättigter Fettsäuren (z.B. 2.065 mg Omega-3 EPA/DHA) steigt der physiologische Vitamin-E-Bedarf der Zellmembranen signifikant an. Das im Stack enthaltene Vitamin E schützt die Omega-3-Fettsäuren direkt vor Oxidation.',
    intakeAdvice: 'Zu einer Mahlzeit einnehmen. Wirkt im antioxidativen Netzwerk optimal zusammen mit Vitamin C, Selen und Coenzym Q10.',
    safetyAndUL: 'EFSA Upper Limit: 300 mg/Tag. Mit 14 mg (100% DGE / D-A-CH für Männer) liegt die Einnahme im absolut sicheren physiologischen Optimalbereich.',
    scientificReference: 'EFSA Journal 2010;8(10):1816 | D-A-CH Referenzwerte'
  },
  'vit-k2': {
    id: 'vit-k2',
    name: 'Vitamin K2 (MK-7)',
    scientificName: 'Menachinon-7 (all-trans)',
    categoryName: 'Vitamine',
    badge: '🦴 Knochen- & Gefäßschutz',
    summary: 'Aktiviert Calcium-Bindungsproteine; lenkt Calcium zielgerichtet in die Knochenmatrix und schützt Arterien vor Verkalkung.',
    biochemistry: 'K2 dient als Kofaktor der Gamma-Glutamylcarboxylase zur Carboxylierung von Osteocalcin (Knochenmineralisierung) und Matrix-Gla-Protein (MGP, stärkster endogener Inhibitor vaskulärer und Weichteilverkalkung). MK-7 besitzt im Vergleich zu K1 eine Halbwertszeit von über 72 Stunden im Blut.',
    plantBasedRelevance: 'Vitamin K2 kommt in relevanter Menge fast nur in tierischen Produkten (Geflügel, Eigelb, gereifter Käse) und japanischem Natto vor. Bei fleischfreier Ernährung und hoher Vitamin-D-Zufuhr ist mikrobiell fermentiertes MK-7 essenziell für die Gefäßgesundheit.',
    intakeAdvice: 'Fettlöslich: Immer zusammen mit Vitamin D3 und gesunden Fetten einnehmen. All-trans-Form garantiert höchste Bioverfügbarkeit.',
    safetyAndUL: 'EFSA hat kein toxisches Upper Limit festgelegt; K2 gilt auch in Dosen von mehreren 100 µg als physiologisch extrem sicher und induziert keine unkontrollierte Blutgerinnung.',
    scientificReference: 'EFSA Journal 2009;7(9):1228 | Thrombosis and Haemostasis 2012'
  },
  'vit-b1': {
    id: 'vit-b1',
    name: 'Vitamin B1',
    scientificName: 'Thiaminhydrochlorid',
    categoryName: 'Vitamine',
    badge: '⚡ Energiestoffwechsel & Nerven',
    summary: 'Schlüsselenzym für den Kohlenhydratabbau, die zelluläre ATP-Gewinnung und die Neurotransmittersynthese.',
    biochemistry: 'Thiamindiphosphat (TDP/TPP) ist der unentbehrliche Kofaktor der Pyruvat-Dehydrogenase und Alpha-Ketoglutarat-Dehydrogenase im Citratzyklus sowie der Transketolase im Pentosephosphatweg (Synthese von NADPH und Ribose für DNA/RNA).',
    plantBasedRelevance: 'Obwohl in Vollkorn und Hülsenfrüchten vorhanden, hemmen pflanzliche Phytate und Gerbstoffe (Kaffee/Tee) die Bioverfügbarkeit. Die Zufuhr sichert die enzymatische Rate bei kohlenhydratreicher pflanzlicher Kost.',
    intakeAdvice: 'Wasserlöslich. Kann morgens oder zu jeder Mahlzeit eingenommen werden.',
    safetyAndUL: 'Kein EFSA Upper Limit; wasserlöslicher Überschuss wird rasch und sicher über die Nieren ausgeschieden.',
    scientificReference: 'EFSA Journal 2010;8(10):1755 | D-A-CH Referenzwerte'
  },
  'vit-b2': {
    id: 'vit-b2',
    name: 'Vitamin B2',
    scientificName: 'Riboflavin / Riboflavin-5-Phosphat (R-5-P)',
    categoryName: 'Vitamine',
    badge: '🔋 Zellatmung & B-Kofaktor',
    summary: 'Zentraler Bestandteil der Atmungskette (FMN/FAD), Fettsäureoxidation und Aktivierung anderer B-Vitamine.',
    biochemistry: 'Riboflavin bildet die prosthetischen Gruppen FMN (Komplex I) und FAD (Komplex II der mitochondrialen Atmungskette). Zudem ist FAD notwendig für die Glutathionreduktase (Regeneration von Glutathion) und die Aktivierung von Pyridoxin (B6) und Folsäure.',
    plantBasedRelevance: 'Milchprodukte und Fleisch sind in der westlichen Mischkost die primären Riboflavinquellen. Bei fleischfreier Ernährung ist eine Supplementierung ein bewährter Schutz vor subklinischen Defiziten. Urin verfärbt sich harmlos leuchtend gelb.',
    intakeAdvice: 'Wasserlöslich. Zu jeder Tageszeit einnehmbar.',
    safetyAndUL: 'Kein EFSA Upper Limit (keine Toxizität bei oraler Aufnahme bekannt).',
    scientificReference: 'EFSA Journal 2010;8(10):1814 | D-A-CH Referenzwerte'
  },
  'vit-b3': {
    id: 'vit-b3',
    name: 'Vitamin B3',
    scientificName: 'Niacin / Nicotinamid',
    categoryName: 'Vitamine',
    badge: '🧬 DNA-Reparatur & NAD+',
    summary: 'Präkursor von NAD+/NADH – unverzichtbar für Zellatmung, ATP-Synthese, DNA-Reparatur und Sirtuin-Aktivität.',
    biochemistry: 'Nicotinamid wird in den zellulären NAD+/NADP+-Pool überführt. NAD+ treibt Hunderte von Redoxreaktionen im Citratzyklus an und dient als Substrat für PARP-Enzyme (Reparatur von DNA-Strangbrüchen) und Sirtuine (epigenetische Langlebigkeitsfaktoren).',
    plantBasedRelevance: 'Die Eigensynthese aus der Aminosäure L-Tryptophan ist mit einem Umwandlungsverhältnis von 60:1 extrem ineffizient. Nicotinamid liefert bioaktives NAD+ ohne gefäßerweiternden "Niacin-Flush".',
    intakeAdvice: 'Als Nicotinamid hervorragend magenverträglich und zu jeder Mahlzeit einsetzbar.',
    safetyAndUL: 'EFSA Upper Limit für Nicotinamid: 900 mg/Tag. Mit 15 mg (94% D-A-CH) liegt die Zufuhr im idealen Sicherheitskorridor.',
    scientificReference: 'EFSA Journal 2014;12(7):3759 | Cell Metabolism NAD+ Reviews'
  },
  'vit-b5': {
    id: 'vit-b5',
    name: 'Vitamin B5',
    scientificName: 'Calcium-D-Pantothenat',
    categoryName: 'Vitamine',
    badge: '⚙️ Coenzym A & Hormonsynthese',
    summary: 'Baustein von Coenzym A (CoA) – zentral für den Fett-, Kohlenhydrat- und Steroidhormon-Stoffwechsel.',
    biochemistry: 'Pantothensäure ist der funktionelle Kern von Coenzym A (CoA) und dem Acyl-Carrier-Protein (ACP). Acetyl-CoA ist die zentrale Drehscheibe des gesamten Intermediärstoffwechsels (Eintritt in den Citratzyklus, Synthese von Cholesterin, Neurotransmittern und Melatonin).',
    plantBasedRelevance: 'Unterstützt die zelluläre Energiegewinnung und die Nebennierenfunktion bei mentalem oder physischem Stress.',
    intakeAdvice: 'Wasserlöslich. Kann morgens oder tagsüber eingenommen werden.',
    safetyAndUL: 'Kein EFSA Upper Limit festgelegt (sehr hohe Toleranz).',
    scientificReference: 'EFSA Journal 2011;9(6):2209 | D-A-CH Referenzwerte'
  },
  'vit-b6': {
    id: 'vit-b6',
    name: 'Vitamin B6',
    scientificName: 'Pyridoxal-5-Phosphat (P-5-P)',
    categoryName: 'Vitamine',
    badge: '🧠 Neurotransmitter & Homocystein',
    summary: 'Kofaktor im Aminosäurestoffwechsel, Hämoglobinbildung, Homocysteinabbau und Neurotransmittersynthese.',
    biochemistry: 'Pyridoxal-5-Phosphat (P-5-P) ist das aktive Coenzym für über 140 Enzyme. Es steuert Decarboxylierungen zur Bildung von Neurotransmittern (Serotonin, Dopamin, GABA) und die Cystathionin-Beta-Synthase zum enzymatischen Abbau des toxischen Homocysteins.',
    plantBasedRelevance: 'Pflanzliches B6 liegt oft als Pyridoxin-Glucosid vor, dessen Bioverfügbarkeit um bis zu 50% reduziert ist. Die direkte Gabe der aktiven Coenzymform P-5-P umgeht hepatische Aktivierungsschritte.',
    intakeAdvice: 'Aktivierte Form P-5-P ist direkt bioverfügbar. Mit 1.6 mg optimal dosiert.',
    safetyAndUL: 'EFSA senkte das Upper Limit 2023 auf 12 mg/Tag. Die Tagesdosis von 1.6 mg liegt weit unterhalb jeglicher neurotoxischer Schwellenwerte.',
    scientificReference: 'EFSA Journal 2023;21(5):8006 | D-A-CH Referenzwerte'
  },
  'vit-b7': {
    id: 'vit-b7',
    name: 'Vitamin B7 (Biotin)',
    scientificName: 'D-Biotin',
    categoryName: 'Vitamine',
    badge: '💇 Keratinstruktur & Carboxylasen',
    summary: 'Kofaktor für Carboxylasen im Fettsäure-, Glukose- und Aminosäurestoffwechsel; Erhalt von Haaren, Haut und Nägeln.',
    biochemistry: 'Biotin dient als prosthetische Gruppe von vier mitochondrialen Carboxylasen (z.B. Pyruvat-Carboxylase, Acetyl-CoA-Carboxylase). Es ermöglicht Carboxylierungsreaktionen zur Gluconeogenese und Fettsäuresynthese sowie die Keratinsynthese in Haarfollikeln.',
    plantBasedRelevance: 'Sichert den Energiestoffwechsel und die Geweberegeneration ab.',
    intakeAdvice: 'Wasserlöslich. Hohe Megadosen (>5.000 µg) können Laborbluttests (z.B. Schilddrüse) stören – die physiologische Dosis von 40 µg ist absolut laborkonform.',
    safetyAndUL: 'Kein EFSA Upper Limit (keine Toxizität bekannt).',
    scientificReference: 'EFSA Journal 2012;10(1):2470 | D-A-CH Referenzwerte'
  },
  'vit-b9': {
    id: 'vit-b9',
    name: 'Vitamin B9 (Folat)',
    scientificName: '5-MTHF (L-Methylfolat / Quatrefolic®)',
    categoryName: 'Vitamine',
    badge: '🧬 Zellteilung & Methylierung',
    summary: 'Unerlässlich für DNA/RNA-Synthese, Zellneubildung, Blutbildung und Remethylierung von Homocystein zu Methionin.',
    biochemistry: '5-Methyltetrahydrofolat (5-MTHF) fungiert als universeller Methylgruppendonor im 1-Kohlenstoff-Stoffwechsel. Zusammen mit Vitamin B12 wandelt es Homocystein in Methionin um, das für die Bildung von S-Adenosylmethionin (SAMe, zellulärer Hauptmethylierer) benötigt wird.',
    plantBasedRelevance: 'Nahrungsfolate sind hitze- und lichtempfindlich. L-Methylfolat (Quatrefolic®) ist im Gegensatz zu synthetischer Folsäure direkt bioaktiv und umgeht den bei bis zu 40% der Bevölkerung vorliegenden MTHFR-Genpolymorphismus (C677T).',
    intakeAdvice: 'Optimal morgens mit Vitamin B12 und Vitamin B6 kombiniert.',
    safetyAndUL: 'EFSA Upper Limit für Folsäure: 1.000 µg/Tag. 200 µg 5-MTHF stellt eine sichere, hoch bioverfügbare Ergänzung dar.',
    scientificReference: 'EFSA Journal 2014;12(11):3893 | Molecular Nutrition & Food Research'
  },
  'vit-b12': {
    id: 'vit-b12',
    name: 'Vitamin B12',
    scientificName: 'Methylcobalamin & Adenosylcobalamin',
    categoryName: 'Vitamine',
    badge: '🌱 Essenziell bei fleischfreier Kost',
    summary: 'Absoluter Schlüsselnährstoff für Myelinscheiden, Nervensystem, Erythrozytenbildung und zelluläre DNA-Synthese.',
    biochemistry: 'B12 ist Kofaktor für die Methionin-Synthase (Zytosol, DNA-Methylierung und Homocystein-Clearance) und die Methylmalonyl-CoA-Mutase (Mitochondrien, Abbau ungeradzahliger Fettsäuren und ATP-Gewinnung). Ein Mangel führt zur irreversiblen Demyelinisierung von Nervenfasern.',
    plantBasedRelevance: 'Kommt in bioverfügbarer Form in keinen Pflanzen vor. Für Nicht-Fleischesser und Nicht-Fischesser ist eine zuverlässige B12-Substitution überlebenswichtig. 50 µg täglich sichert auch bei eingeschränkter Intrinsic-Factor-Bindung eine ausreichende passive Diffusion im Darm.',
    intakeAdvice: 'Zu jeder Tageszeit einnehmbar. Bioaktive Methyl- und Adenosyl-Formen belasten den Körper im Gegensatz zu Cyanocobalamin nicht mit Cyanidgruppen.',
    safetyAndUL: 'EFSA: Kein toxisches Limit bekannt. Wasserlöslicher Überschuss wird problemlos ausgeschieden.',
    scientificReference: 'EFSA Journal 2015;13(7):4150 | American Journal of Clinical Nutrition'
  },
  'vit-c': {
    id: 'vit-c',
    name: 'Vitamin C',
    scientificName: 'Ascorbinsäure / Calciumascorbat (580 mg)',
    categoryName: 'Vitamine',
    badge: '🍊 Kollagensynthese & Eisen-Booster',
    summary: 'Starkes Antioxidans, Enzymkofaktor für die Kollagensynthese, Immunsystem und 3- bis 4-fache Steigerung der pflanzlichen Eisenaufnahme.',
    biochemistry: 'Ascorbat hält das Eisen in Prolyl- und Lysylhydroxylasen im reduzierten Fe2+-Zustand, was für die Vernetzung der Kollagen-Dreifachhelix zwingend nötig ist. Zudem reduziert es dreiwertiges pflanzliches Nicht-Häm-Eisen (Fe3+) im Magen-Darm-Trakt zu bioverfügbarem Fe2+.',
    plantBasedRelevance: 'Da pflanzliches Eisen schlechter resorbiert wird als tierisches Häm-Eisen, ist Vitamin C der potenteste physiologische Hebel zur Maximierung der Eisenaufnahme aus Nahrung und Multinährstoffen.',
    intakeAdvice: 'Gepuffertes Calciumascorbat ist magenfreundlich. Ideal zusammen mit Mahlzeiten oder Eisen eintragen.',
    safetyAndUL: 'EFSA hat mangels Toxizität keinen numerischen Upper Limit (UL) festgelegt. Der etablierte US IOM (Institute of Medicine) Grenzwert liegt bei 2.000 mg/Tag. Mit 580 mg Gesamtzufuhr (527% DGE) absolut sicher und optimal im wirksamen Bereich.',
    scientificReference: 'EFSA Journal 2013;11(11):3418 | US IOM Dietary Reference Intakes | D-A-CH Referenzwerte'
  },

  // =========================================================================
  // MINERALSTOFFE & SPURENELEMENTE (11)
  // =========================================================================
  'calcium': {
    id: 'calcium',
    name: 'Calcium',
    scientificName: 'Calcium-Bisglycinat (120 mg) + Calciumcitrat (600 mg)',
    categoryName: 'Mineralstoffe & Spurenelemente',
    badge: '🦴 720 mg Knochendichte & Muskel',
    summary: 'Hauptmineral für Knochen- und Zahnmatrix, neuromuskuläre Reizübertragung, Blutgerinnung und Muskelkontraktion.',
    biochemistry: '99% des Calciums sind als Hydroxylapatit im Skelett gespeichert. Das ionisierte Calcium (Ca2+) im Zytosol steuert Muskelkontraktionen, Neurotransmitterausschüttung an Synapsen und Enzymaktivierungen.',
    plantBasedRelevance: 'Mit 2 Tabletten Warnke Calciumcitrat (600 mg) und Watson Male Essentials (120 mg) erreichst du 720 mg (72% des DGE / D-A-CH Tagesbedarfs von 1.000 mg). Organisches Calciumcitrat besitzt eine magensäureunabhängige, herausragende Resorption.',
    intakeAdvice: 'Über den Tag verteilen (z.B. 1 Tablette mittags, 1 Tablette abends zu den Mahlzeiten) und im Verbund mit Vitamin D3 & K2 für optimalen Knocheneinbau.',
    safetyAndUL: 'EFSA Upper Limit: 2.500 mg/Tag. Mit 720 mg liegst du im perfekten physiologischen Wohlfühlbereich.',
    scientificReference: 'EFSA Journal 2015;13(5):4101 | D-A-CH Referenzwerte 2020'
  },
  'magnesium': {
    id: 'magnesium',
    name: 'Magnesium',
    scientificName: 'Magnesiumbisglycinat (400 mg)',
    categoryName: 'Mineralstoffe & Spurenelemente',
    badge: '🌙 300+ Enzyme & Nervenruhe',
    summary: 'Aktiviert über 300 Enzyme, entspannt Muskulatur und Gefäße, reguliert den Schlaf und ist Kofaktor von Vitamin D3.',
    biochemistry: 'Magnesium ist zwingend an ATP gebunden (Mg-ATP-Komplex) und ermöglicht jede zelluläre Energieübertragung. Es wirkt als natürlicher NMDA-Rezeptor-Blocker im Gehirn beruhigend auf das Nervensystem und ist Kofaktor für alle Vitamin-D-aktivierenden Enzyme.',
    plantBasedRelevance: 'Die organische Chelat-Form Magnesiumbisglycinat besitzt eine exzellente Bioverfügbarkeit, passiert die Darmwand über Aminosäure-Transporter und schont die Verdauung (keine laxative Wirkung wie Magnesiumoxid).',
    intakeAdvice: 'Optimal abends vor dem Schlafen einnehmen (unterstützt parasympathische Aktivität und Schlafqualität).',
    safetyAndUL: 'BfR empfiehlt 250 mg aus isolierten Nahrungsergänzungsmitteln; bei hoch bioverfügbarem Bisglycinat sind 400 mg (114% DGE) für aktive Erwachsene hervorragend verträglich.',
    scientificReference: 'EFSA Journal 2015;13(7):4186 | Magnesium Research Journal'
  },
  'eisen': {
    id: 'eisen',
    name: 'Eisen',
    scientificName: 'Eisenbisglycinat (6.0 mg)',
    categoryName: 'Mineralstoffe & Spurenelemente',
    badge: '🩸 Sauerstofftransport & Hämoglobin',
    summary: 'Zentralatom des Hämoglobins und Myoglobins für den Sauerstofftransport; Kofaktor der mitochondrialen Atmungskette.',
    biochemistry: 'Eisen ist essenzieller Bestandteil von Eisen-Schwefel-Clustern in den Komplexen I, II und III der mitochondrialen Atmungskette und des Häm-Rings zur Sauerstoffbindung in Erythrozyten.',
    plantBasedRelevance: 'Nicht-Fleischesser nehmen nur 3-wertiges Nicht-Häm-Eisen auf. Eisenbisglycinat ist cheliert, wird 3- bis 4-mal besser resorbiert als anorganische Eisensalze und verursacht keine Magen-Darm-Irritationen.',
    intakeAdvice: 'Gleichzeitige Zufuhr von Vitamin C maximiert die Aufnahme. Kaffee und schwarzer Tee sollten im Abstand von 1-2 Stunden getrunken werden.',
    safetyAndUL: 'EFSA hat keinen numerischen Upper Limit für Eisen festgelegt (Bewertung über Verträglichkeit). Der US IOM Grenzwert liegt bei 45 mg/Tag. 6.0 mg Eisenbisglycinat (60% DGE für Männer) ist die ideale physiologische Sicherheitsdosis ohne Überladungsrisiko.',
    scientificReference: 'EFSA Journal 2015;13(10):4254 | US IOM Iron Safety | Blood Journal'
  },
  'zink': {
    id: 'zink',
    name: 'Zink',
    scientificName: 'Zinkbisglycinat (10 mg)',
    categoryName: 'Mineralstoffe & Spurenelemente',
    badge: '🛡️ Testosteron & Immunsystem',
    summary: 'Katalytischer Kofaktor für >300 Enzyme, Zinkfinger-Proteine (DNA-Transkription), Wundheilung und Testosteronspiegel.',
    biochemistry: 'Zink stabilisiert die Tertiärstruktur von Zinkfinger-Transkriptionsfaktoren, ist Bestandteil der Superoxiddismutase (SOD1, Radikalschutz) und hemmt die Aromatase, was den Erhalt physiologischer Testosteronspiegel unterstützt.',
    plantBasedRelevance: 'Pflanzliche Ernährung enthält Phytate (in Getreide/Hülsenfrüchten), die Zink im Darm unlöslich binden. Cheliertes Zinkbisglycinat umgeht diese Phytat-Blockade weitgehend.',
    intakeAdvice: 'Nicht auf komplett nüchternen Magen einnehmen. Kupfer im Multinährstoff (0.5 mg) hält das Zink/Kupfer-Gleichgewicht intakt.',
    safetyAndUL: 'EFSA Tolerable Upper Limit: 25 mg/Tag. Mit 10 mg (71% DGE / D-A-CH für Männer) exakt auf eine sichere tägliche Zinkbasis abgestimmt.',
    scientificReference: 'EFSA Journal 2014;12(10):3844 | D-A-CH Referenzwerte'
  },
  'jod': {
    id: 'jod',
    name: 'Jod',
    scientificName: 'Kaliumjodid (150 µg)',
    categoryName: 'Mineralstoffe & Spurenelemente',
    badge: '🦋 Schilddrüsenhormone (T3/T4)',
    summary: 'Zwingender Baustein der Schilddrüsenhormone Thyroxin (T4) und Trijodthyronin (T3) für Grundumsatz und Thermogenese.',
    biochemistry: 'Jodid wird in den Thyreozyten über den Natrium-Jodid-Symporter (NIS) aufgenommen und durch Thyreoperoxidase (TPO) an Tyrosinreste im Thyreoglobulin gebunden, um T3 und T4 zu synthetisieren.',
    plantBasedRelevance: 'Ohne den Konsum von Meeresfisch oder jodiertem Speisesalz ist Mitteleuropa ein klassisches Jodmangelgebiet. Pflanzliche Böden sind jodarm. 150 µg sichert die euthyreote Schilddrüsenfunktion optimal ab.',
    intakeAdvice: 'Wirkt eng mit Selen zusammen (Selen wird für Dejodasen zur T4->T3 Aktivierung benötigt).',
    safetyAndUL: 'EFSA Upper Limit: 600 µg/Tag. 150 µg entspricht 75% der DGE / D-A-CH Empfehlung für Erwachsene (200 µg) und ist absolut sicher.',
    scientificReference: 'EFSA Journal 2014;12(7):3760 | D-A-CH Referenzwerte'
  },
  'selen': {
    id: 'selen',
    name: 'Selen',
    scientificName: 'L-Selenmethionin (70 µg)',
    categoryName: 'Mineralstoffe & Spurenelemente',
    badge: '🛡️ Glutathionperoxidase & Schilddrüse',
    summary: 'Baustein von Selenocystein in 25 Selenoproteinen (Glutathionperoxidase, Dejodinasen, Thioredoxinreduktase).',
    biochemistry: 'Selenocystein im katalytischen Zentrum der Glutathionperoxidase neutralisiert toxisches Wasserstoffperoxid und Lipidhydroperoxide. Iodthyronin-Dejodinasen aktivieren das Schilddrüsenhormon T4 in die stoffwechselaktive T3-Form.',
    plantBasedRelevance: 'Mitteleuropäische Böden sind eiszeitbedingt extrem selenarm, weshalb heimisches pflanzliches Getreide und Gemüse kaum Selen enthalten. Selenmethionin gleicht dieses Defizit verlässlich aus.',
    intakeAdvice: 'Organisches Selenmethionin wird mit hoher Quote in den Proteinpool inkorporiert.',
    safetyAndUL: 'EFSA Upper Limit: 255 µg/Tag. Mit 70 µg (100% DGE / D-A-CH) im optimalen Bereich.',
    scientificReference: 'EFSA Journal 2023;21(1):7704 | D-A-CH Referenzwerte'
  },
  'kupfer': {
    id: 'kupfer',
    name: 'Kupfer',
    scientificName: 'Kupferbisglycinat (0.5 mg)',
    categoryName: 'Mineralstoffe & Spurenelemente',
    badge: '🔬 Eisenverwertung & Kollagen',
    summary: 'Bestandteil von Ceruloplasmin (Eisenoxidation), Cytochrom-c-Oxidase (Atmungskette) und Lysyloxidase (Kollagenvernetzung).',
    biochemistry: 'Kupfer ermöglicht über Ceruloplasmin die Bindung von Eisen an Transferrin und ist Bestandteil von Komplex IV der Atmungskette sowie der Superoxiddismutase (Cu/Zn-SOD).',
    plantBasedRelevance: 'Hohe Zinkgaben können die Kupferaufnahme hemmen (über intestinale Metallothionein-Induktion). Die Zufuhr von 0.5 mg Kupferbisglycinat sichert das physiologische 10:1 Zink-Kupfer-Verhältnis.',
    intakeAdvice: 'Organisches Bisglycinat verhindert Resorptionskonflikte.',
    safetyAndUL: 'EFSA Upper Limit: 5.0 mg/Tag. 0.5 mg (50% DGE) ist absolut sicher.',
    scientificReference: 'EFSA Journal 2015;13(4):4089 | D-A-CH Referenzwerte'
  },
  'mangan': {
    id: 'mangan',
    name: 'Mangan',
    scientificName: 'Mangangluconat (1.0 mg)',
    categoryName: 'Mineralstoffe & Spurenelemente',
    badge: '🦴 Knorpelaufbau & Mn-SOD',
    summary: 'Kofaktor für Glycosyltransferasen im Knorpel- und Bindegewebsaufbau sowie der mitochondrialen Mn-SOD.',
    biochemistry: 'Aktiviert Enzyme zur Proteoglykan- und Chondroitinsulfat-Synthese im Gelenkknorpel und bildet das Herzstück der mitochondrialen Mangan-Superoxiddismutase (Mn-SOD) zum Schutz vor Sauerstoffradikalen.',
    plantBasedRelevance: 'Unterstützt zusammen mit Glycin, Hyaluronsäure und Vitamin C die Gelenk- und Sehnenregeneration.',
    intakeAdvice: 'Zu einer Mahlzeit einnehmen.',
    safetyAndUL: 'EFSA hat mangels ausreichender Dosis-Wirkungs-Daten keinen numerischen UL festgelegt. Der etablierte US IOM Grenzwert liegt bei 11 mg/Tag. 1.0 mg (50% DGE / D-A-CH) liefert eine sichere Basisabsicherung.',
    scientificReference: 'EFSA Journal 2013;11(5):3419 | US IOM DRI Manganese | D-A-CH Referenzwerte'
  },
  'chrom': {
    id: 'chrom',
    name: 'Chrom',
    scientificName: 'Chrompicolinat (20 µg)',
    categoryName: 'Mineralstoffe & Spurenelemente',
    badge: '🩸 Insulinsensitivität & Glukose',
    summary: 'Bestandteil des Chromodulins – verstärkt die Signalwirkung von Insulin an Zellrezeptoren und stabilisiert den Blutzucker.',
    biochemistry: 'Das Peptid Chromodulin bindet an die zytosolische Tyrosinkinase-Domäne des aktivierten Insulinrezeptors und vervielfacht dessen Signalübertragung, was die GLUT-4-Translokation zur Glukoseaufnahme in Muskelzellen fördert.',
    plantBasedRelevance: 'Chrompicolinat weist die höchste Bioverfügbarkeit aller Chromverbindungen auf und unterstützt den Kohlenhydratstoffwechsel bei pflanzlicher Ernährung.',
    intakeAdvice: 'Zu einer Mahlzeit einnehmen.',
    safetyAndUL: 'EFSA hat keinen numerischen UL für trivalentes Chrom aus Nahrung/NEM festgelegt (TDI: 300 µg/kg KG). Internationale Orientierungs- und Sicherheitswerte (WHO / BfR / UK EVM) liegen bei 250 µg/Tag. 20 µg (67% DGE / D-A-CH) ist optimal und absolut sicher.',
    scientificReference: 'EFSA Journal 2014;12(10):3845 | WHO / BfR Referenzwerte | Diabetes Care Journal'
  },
  'molybdaen': {
    id: 'molybdaen',
    name: 'Molybdän',
    scientificName: 'Natriummolybdat (25 µg)',
    categoryName: 'Mineralstoffe & Spurenelemente',
    badge: '🔬 Schwefel- & Purin-Clearing',
    summary: 'Kofaktor für Sulfitoxidase und Xanthinoxidase – essenziell für den Abbau schwefelhaltiger Aminosäuren und Harnsäure.',
    biochemistry: 'Molybdän ist Bestandteil des Molybdän-Kofaktors (Moco), der in der Sulfitoxidase toxisches Sulfit in Sulfat überführt und in der Xanthinoxidase den Purinabbau reguliert.',
    plantBasedRelevance: 'Sichert die Entgiftung schwefelhaltiger Stoffwechselprodukte bei proteinreicher Kost ab.',
    intakeAdvice: 'Wasserlöslich, zu jeder Tageszeit.',
    safetyAndUL: 'EFSA Upper Limit: 600 µg/Tag. 25 µg (50% DGE / D-A-CH) ist völlig unbedenklich.',
    scientificReference: 'EFSA Journal 2013;11(10):3420 | D-A-CH Referenzwerte'
  },
  'bor': {
    id: 'bor',
    name: 'Bor',
    scientificName: 'Borat / Natriumborat (0 mg - Offen)',
    categoryName: 'Mineralstoffe & Spurenelemente',
    badge: '⚡ SHBG-Senkung & Freies Testosteron',
    summary: 'Essentieller Kofaktor zur Modulation von Steroidhormonen (senkt SHBG für mehr freies Testosteron) und Knochenstoffwechsel.',
    biochemistry: 'Bor senkt im Serum das Sexualhormon-bindende Globulin (SHBG), wodurch der Anteil an freiem, biologisch aktivem Testosteron signifikant ansteigt. Zudem reduziert es die renale Ausscheidung von Calcium und Magnesium.',
    plantBasedRelevance: 'Nicht im aktuellen Stack enthalten. Eine gezielte Ergänzung von 3.0 mg Bor kann bei sportlich aktiven Männern zur Hormonoptimierung und Knorpelstabilisierung sinnvoll sein.',
    intakeAdvice: 'Morgens zu einer Mahlzeit einnehmen. Zyklen von 6-8 Wochen mit 1-2 Wochen Pause sind in Studien gängige Praxis.',
    safetyAndUL: 'EFSA Upper Limit: 10 mg/Tag. Dosierungen von 3 bis 6 mg gelten als sicher und wirksam.',
    scientificReference: 'Journal of Trace Elements in Medicine and Biology 2011;25(4):216-224'
  },

  // =========================================================================
  // AMINOSÄUREN, OMEGA-3 & PERFORMANCE (15)
  // =========================================================================
  'omega-3': {
    id: 'omega-3',
    name: 'Omega-3 (EPA & DHA)',
    scientificName: 'BalanceOil+ (1.069 mg EPA + 569 mg DHA + 427 mg DPA)',
    categoryName: 'Aminosäuren, Omega-3 & Performance',
    badge: '🧠 Zellmembranen & Entzündungsbremse',
    summary: 'Essenzielle marine Fettsäuren für Gehirnstruktur, Netzhaut, Herzfunktion und Vorläufer entzündungsauflösender Resolvine.',
    biochemistry: 'EPA und DHA werden in Phospholipide aller Zellmembranen eingebaut, erhöhen deren Fluidität und verdrängen Arachidonsäure. Aus EPA entstehen entzündungshemmende Eicosanoide (Serie-3-Prostaglandine) und spezialisierte pro-resolvierende Mediatoren (SPMs: Resolvine, Protectine).',
    plantBasedRelevance: 'Pflanzliches ALA (aus Leinöl/Walnüssen) wird im Körper nur zu <5% in EPA und <0.5% in DHA umgewandelt. Zinzino BalanceOil+ liefert vorgeformtes EPA/DHA kombiniert mit Oliven-Polyphenolen, die die Fettsäuren vor Oxidation im Blut schützen.',
    intakeAdvice: '10 ml flüssig zu einer Hauptmahlzeit einnehmen. Synergie mit fettlöslichen Vitaminen (D3, E, K2).',
    safetyAndUL: 'EFSA stuft eine Zufuhr von bis zu 5.000 mg (5 g) EPA+DHA pro Tag als absolut sicher für Erwachsene ein. 2.065 mg ist eine hochpotente Dosis.',
    scientificReference: 'EFSA Journal 2012;10(7):2815 | Circulation Journal 2019'
  },
  'glycin': {
    id: 'glycin',
    name: 'Glycin',
    scientificName: 'Glycin (Diamond® 4.000 mg in CollaSyn®)',
    categoryName: 'Aminosäuren, Omega-3 & Performance',
    badge: '✨ Kollagen-Hauptbaustein & Schlaf',
    summary: 'Jede dritte Aminosäure in Kollagen ist Glycin; zudem Neurotransmitter, Glutathion-Baustein und Schlafoptimierer.',
    biochemistry: 'Glycin ist die kleinste Aminosäure und unverzichtbar für die enge Dreifachhelix-Windung von Kollagen (Gly-X-Y-Sequenz). Es bildet zusammen mit Glutamin und Cystein das Master-Antioxidans Glutathion und wirkt an Glycin-Rezeptoren im ZNS hemmend (beruhigend).',
    plantBasedRelevance: 'Kollagenreiches Bindegewebe, Gelatine und Knochenbrühe fehlen bei fleisch- und fischfreier Kost völlig. Der Körper hat ein endogenes Glycin-Defizit von ca. 3-4 g/Tag. CollaSyn® deckt dies mit 4.000 mg vollständig pflanzlich ab.',
    intakeAdvice: 'Morgens im Shake oder abends vor dem Schlafen (senkt die Körperkerntemperatur und fördert den Tiefschlaf).',
    safetyAndUL: 'Sehr hohe physiologische Sicherheit; Dosen bis zu 15 g/Tag zeigen in Studien keinerlei Toxizität.',
    scientificReference: 'Amino Acids Journal 2018;50(12):1653 | Sleep and Biological Rhythms'
  },
  'hyaluron': {
    id: 'hyaluron',
    name: 'Hyaluronsäure',
    scientificName: 'HAPLEX®Plus Natriumhyaluronat (200 mg in CollaSyn®)',
    categoryName: 'Aminosäuren, Omega-3 & Performance',
    badge: '💧 Feuchtigkeitsmatrix & Gelenke',
    summary: 'Hochmolekulares Glykosaminoglykan – bindet das bis zu 1.000-fache seines Eigengewichts an Wasser in Haut und Gelenkknorpel.',
    biochemistry: 'Hyaluronsäure ist Hauptbestandteil der Synovialflüssigkeit (Gelenkschmiere) und der extrazellulären Matrix der Dermis. Über CD44-Rezeptoren stimuliert oral zugeführtes Hyaluronat Chondrozyten und Fibroblasten zur endogenen Neusynthese.',
    plantBasedRelevance: 'Gewonnen durch biotechnologische Fermentation (vegan). Schützt Gelenkknorpel bei sportlicher Belastung und hydratisiert die Haut von innen.',
    intakeAdvice: 'Mit reichlich Flüssigkeit (mind. 250-300 ml Wasser) einnehmen.',
    safetyAndUL: 'Gilt als extrem sicher und hypoallergen; EFSA-bewertete Studien nutzen 100-200 mg/Tag.',
    scientificReference: 'Nutrition Journal 2014;13:70 | Journal of Clinical Biochemistry and Nutrition'
  },
  'creatine': {
    id: 'creatine',
    name: 'Kreatin',
    scientificName: 'Kreatin-Monohydrat (Creapure® 3.000 mg)',
    categoryName: 'Aminosäuren, Omega-3 & Performance',
    badge: '⚡ ATP-Resynthese & Gehirnleistung',
    summary: 'Phosphatkreatin-Speicher für sofortige ATP-Bereitstellung bei Schnellkraft, Muskelarbeit und neuronaler Kognition.',
    biochemistry: 'Kreatin wird durch Kreatinkinase zu Phosphokreatin phosphoryliert. Bei zellulärem Energiemangel überträgt es seine Phosphatgruppe in Millisekunden auf ADP zur Regeneration von ATP (universelle Energiewährung).',
    plantBasedRelevance: 'Da Kreatin natürlicherweise ausschließlich in Fleisch und Fisch vorkommt, haben Nicht-Fleischesser um 20-30% niedrigere Muskel- und Gehirnkreatinspeicher. Nicht-Fleischesser profitieren daher kognitiv und körperlich am stärksten von Creapure®!',
    intakeAdvice: 'Täglich 3.000 mg (1 Messlöffel) mit Wasser oder im Shake einnehmen. Einnahmezeitpunkt ist flexibel.',
    safetyAndUL: 'Creapure® (Alzchem Deutschland) ist das weltweit reinste Kreatin und das meistuntersuchte Supplement der Welt mit belegter Langzeitsicherheit.',
    scientificReference: 'EFSA Journal 2011;9(7):2303 | International Society of Sports Nutrition (ISSN)'
  },
  'cholin': {
    id: 'cholin',
    name: 'Cholin',
    scientificName: 'Cholinbitartrat (450 mg reines Cholin)',
    categoryName: 'Omega-3 & Vitalstoffe',
    badge: '🧠 Acetylcholin & Leber-Fettstoffwechsel',
    summary: 'Vorstufe des Gedächtnis-Neurotransmitters Acetylcholin und Phosphatidylcholin für Leber und Zellmembranen.',
    biochemistry: 'Cholin wird für die Synthese von Acetylcholin (Fokus, Lernen, neuromuskuläre Übertragung) und Phosphatidylcholin (Hauptphospholipid aller Membranen) benötigt. Über Betain dient es zudem als Methylgruppendonor zur Senkung von Homocystein.',
    plantBasedRelevance: 'Die reichhaltigsten Cholinquellen sind Eigelb und Rinderleber. Pflanzliche Lebensmittel liefern deutlich geringere Konzentrationen. 450 mg deckt die EFSA-Zufuhrempfehlung (400 mg) für Erwachsene optimal ab.',
    intakeAdvice: 'Morgens oder mittags zu einer Mahlzeit einnehmen.',
    safetyAndUL: 'EFSA Adequate Intake (AI): 400 mg/Tag. Der US IOM Tolerable Upper Intake Level liegt bei 3.500 mg/Tag. Mit 450 mg (113% EFSA AI) erreichst du die perfekte Zieldosis bei maximalem Sicherheitsabstand.',
    scientificReference: 'EFSA Journal 2016;14(8):4484 | US IOM Choline Dietary Reference Intakes | Nutrients Journal'
  },
  'polyphenols': {
    id: 'polyphenols',
    name: 'Oliven-Polyphenole',
    scientificName: 'Hydroxytyrosol & Oleuropein (2.9 mg in BalanceOil+)',
    categoryName: 'Omega-3 & Vitalstoffe',
    badge: '🌿 LDL-Lipidschutz & Gefäßgesundheit',
    summary: 'Hochpotente Phenolverbindungen aus vorzeitig geerntetem Olivenöl – schützen Blutfette vor oxidativem Stress.',
    biochemistry: 'Hydroxytyrosol bindet an LDL-Partikel und verhindert deren Oxidation zu oxLDL (Schlüsselfaktor in der Entstehung atherosklerotischer Plaques). Zudem aktiviert es den Nrf2-Signalweg zur Hochregulation körpereigener Schutzenzyme.',
    plantBasedRelevance: 'Verhindert die Oxidation des flüssigen Omega-3-Öls in der Flasche sowie nach der Resorption im Blutkreislauf.',
    intakeAdvice: 'In Zinzino BalanceOil+ direkt im Verbund mit EPA/DHA enthalten.',
    safetyAndUL: 'EFSA bestätigt den Health Claim ab 5 mg Hydroxytyrosol/Tag; absolut natürlicher Nahrungsbestandteil.',
    scientificReference: 'EFSA Journal 2011;9(4):2033 | Atherosclerosis Journal'
  },
  'carnitine': {
    id: 'carnitine',
    name: 'Acetyl-L-Carnitin (ALCAR)',
    scientificName: 'Acetyl-L-Carnitin (500 mg aus GEN / 3.000 mg pro 6 Kapseln)',
    categoryName: 'Aminosäuren & Protein',
    badge: '🔥 Mitochondriale Fettverbrennung & ZNS',
    summary: 'Bedingt essentielle Aminosäurenverbindung in acetylierter Form – überwindet die Blut-Hirn-Schranke und transportiert Fettsäuren in die Mitochondrien.',
    biochemistry: 'Acetyl-L-Carnitin liefert Acetylgruppen für die Synthese des zentralen Neurotransmitters Acetylcholin und schleust langkettige Fettsäuren über die Carnitin-Palmitoyl-Transferase (CPT-1) in die Mitochondrienmatrix zur Beta-Oxidation (ATP-Generierung).',
    plantBasedRelevance: '95% des Carnitins stammen in der Standardernährung aus rotem Fleisch. Für Nicht-Fleischesser liefert 1 Kapsel GEN ALCAR täglich 500 mg hoch bioverfügbares Carnitin (bei Bedarf flexibel auf 2 Kapseln = 1.000 mg oder bis zur vollen Tagesdosis von 6 Kapseln = 3.000 mg steigerbar).',
    intakeAdvice: 'Morgens vor dem Frühstück oder ca. 30–45 Minuten vor dem Training mit Wasser einnehmen.',
    safetyAndUL: 'Für L-Carnitin existiert kein gesetzlicher EFSA Upper Limit. Das in Humanstudien und toxikologischen Reviews etablierte Observed Safe Level (OSL nach Hathcock & Shao / CRN) liegt bei 2.000–3.000 mg/Tag. 500 mg ALCAR ist physiologisch sicher und flexibel dosierbar.',
    scientificReference: 'Regulatory Toxicology and Pharmacology (Hathcock & Shao) | American Journal of Clinical Nutrition'
  },
  'taurine': {
    id: 'taurine',
    name: 'Taurin',
    scientificName: '2-Aminoethansulfonsäure (0 mg - Offen)',
    categoryName: 'Aminosäuren & Protein',
    badge: '❤️ Kardiometabolismus & Zellschutz',
    summary: 'Bedingt essentielle Aminosulfonsäure – reguliert zellulären osmotischen Druck, Gallensäurenkonjugation und Kardiomyozyten.',
    biochemistry: 'Taurin moduliert zelluläre Calciumströme im Herzmuskel, bindet an GABA-A-Rezeptoren im Gehirn, konjugiert Gallensäuren (Taurocholsäure zur Fettverdauung) und schützt Mitochondrien vor oxidativem Stress.',
    plantBasedRelevance: 'Taurin kommt in pflanzlichen Lebensmitteln nicht vor (Gehalt = 0 mg). Vegetarier und Veganer weisen signifikant niedrigere Plasma- und Urin-Taurinspiegel auf. Aktuelle Studien (Science 2023) identifizieren Taurin als Schlüsselfaktor für gesunde Langlebigkeit.',
    intakeAdvice: '500 bis 1.500 mg täglich, ideal morgens oder tagsüber.',
    safetyAndUL: 'EFSA bestätigte in Sicherheitsgutachten einen No-Observed-Adverse-Effect-Level (NOAEL) von 1.000 mg/kg KG/Tag; eine Zufuhr von bis zu 3.000 mg (3 g)/Tag gilt als wissenschaftlich absolut sicher.',
    scientificReference: 'EFSA Journal 2009;935:1-31 | Science 2023;380(6649):eabn9257'
  },
  'carnosine': {
    id: 'carnosine',
    name: 'Carnosin / Beta-Alanin',
    scientificName: 'Beta-Alanyl-L-Histidin (0 mg - Offen)',
    categoryName: 'Aminosäuren & Protein',
    badge: '🛡️ Protonenpuffer & Anti-Glykation',
    summary: 'Intrazelluläres Dipeptid – puffert H+-Ionen bei intensiver Muskelarbeit und schützt Proteine vor Verzuckerung (AGEs).',
    biochemistry: 'Carnosin besitzt einen pKa-Wert von 6.83 und ist der stärkste physiologische Säurepuffer im Zytosol von Typ-II-Muskelfasern gegen Laktat-induzierten Leistungsabfall. Zudem cheliert es Übergangsmetalle und hemmt die Glykation von Proteinen im Gehirn.',
    plantBasedRelevance: 'Kommt ausschließlich in tierischem Muskelgewebe vor. Nicht-Fleischesser haben nachweislich ca. 50% weniger Carnosin in den Muskeln. Durch Gabe von Beta-Alanin oder L-Carnosin kann der Speicher wieder aufgefüllt werden.',
    intakeAdvice: 'Beta-Alanin (1.500-3.000 mg/Tag) teilt man am besten auf 2 Dosen auf, um harmloses Kribbeln (Parästhesie) zu vermeiden.',
    safetyAndUL: 'Sehr hohes Sicherheitsprofil in internationalen Sportstudien.',
    scientificReference: 'Amino Acids Journal 2012;43(1):5-12 | ISSN Position Stand'
  },
  'coq10': {
    id: 'coq10',
    name: 'Coenzym Q10 (vegan)',
    scientificName: 'Coenzym Q10 (200 mg aus Fermentation)',
    categoryName: 'Omega-3 & Vitalstoffe',
    badge: '🔋 200 mg ATP-Atmungskette & Herzschutz',
    summary: 'Zentraler Elektronenüberträger in der inneren Mitochondrienmembran (Komplexe I/II -> III) und starkes lipidlösliches Antioxidans.',
    biochemistry: 'CoQ10 transferiert Elektronen zur ATP-Synthase und treibt so die zelluläre Energieproduktion in Herz, Muskeln und Gehirn an. Es recycelt oxidiertes Vitamin E und schützt mitochondriale Membranen direkt vor freien Radikalen.',
    plantBasedRelevance: 'Die Hauptnahrungsquellen sind tierische Innereien (Herz, Leber) und fetter Fisch. Durch die 200 mg veganes Fermentations-Q10 schließt du diese Versorgungslücke mit einer klinisch hochwirksamen Dosis.',
    intakeAdvice: 'Fettlöslich: Immer morgens zum Frühstück mit Fettquelle oder zum Omega-3 BalanceOil+ einnehmen.',
    safetyAndUL: 'Für CoQ10 existiert kein gesetzlicher EFSA Upper Limit. Das wissenschaftlich etablierte Observed Safe Level (OSL nach Hathcock & Shao) liegt bei 300 mg/Tag. Mit 200 mg liegt deine Zufuhr im optimalen, klinisch bestens erforschten Bereich.',
    scientificReference: 'Regulatory Toxicology and Pharmacology 2006;45(3):282-288 (Hathcock & Shao CoQ10 Safety) | BioFactors Journal'
  },
  'nac': {
    id: 'nac',
    name: 'N-Acetylcystein (NAC)',
    scientificName: 'N-Acetyl-L-Cystein (0 mg - Offen)',
    categoryName: 'Aminosäuren & Protein',
    badge: '🛡️ Glutathion-Booster & Entgiftung',
    summary: 'Geschwindigkeitsbestimmender Vorläufer für Glutathion – das wichtigste körpereigene intrazelluläre Entgiftungsmolekül.',
    biochemistry: 'NAC liefert bioverfügbares L-Cystein für die Glutamat-Cystein-Ligase, den limitierenden Schritt der zellulären Glutathionsynthese (GSH). GSH neutralisiert freie Radikale, entgiftet Xenobiotika in der Leber (Phase II) und schützt Lunge und Nieren.',
    plantBasedRelevance: 'Fleisch liefert hohe Dosen schwefelhaltiger Aminosäuren (Methionin/Cystein). Bei fleischfreier Kost ist Cystein oft der limitierende Faktor für die maximale Glutathionbildung.',
    intakeAdvice: '600 mg täglich, ideal morgens mit Wasser oder Vitamin C.',
    safetyAndUL: 'Sehr gut erforschter Arznei- und Nährstoff mit exzellentem Sicherheitsprofil bei 600-1.200 mg/Tag.',
    scientificReference: 'Redox Biology 2020 | Antioxidants & Redox Signaling'
  },
  'astaxanthin': {
    id: 'astaxanthin',
    name: 'Astaxanthin (AstaPure®)',
    scientificName: 'Natürliches Astaxanthin (12 mg aus Vitabay)',
    categoryName: 'Omega-3 & Vitalstoffe',
    badge: '👁️ 12 mg Membran-Zellschutz & Blut-Hirn-Schranke',
    summary: 'Das stärkste Carotinoid der Natur (6.000x stärker als Vitamin C) – durchspannt Zellmembranen und schützt Augen, Gehirn und Gefäße.',
    biochemistry: 'Aufgrund seiner polaren Endgruppen legt sich Astaxanthin quer durch die Lipiddoppelschicht der Zellmembranen und schützt sowohl den inneren als auch den äußeren Zellraum vor Lipidperoxidation. Es passiert mühelos die Blut-Hirn- und Blut-Netzhaut-Schranke.',
    plantBasedRelevance: 'Kommt in der Natur über die Nahrungskette primär in Wildlachs vor. Die hochdosierten 12 mg veganes Astaxanthin aus der Mikroalge Haematococcus pluvialis übertreffen die Zufuhr eines üblichen Fischkonsums um ein Vielfaches.',
    intakeAdvice: 'Fettlöslich: Zu einer Mahlzeit mit Fett oder direkt zusammen mit Zinzino BalanceOil+ einnehmen.',
    safetyAndUL: 'EFSA bewertet bis zu 8–12 mg natürliches Algen-Astaxanthin pro Tag für Erwachsene als sicher und exzellent verträglich.',
    scientificReference: 'EFSA Journal 2020;18(2):5993 | Marine Drugs Journal | Nutrients 2020'
  },
  'prolin': {
    id: 'prolin',
    name: 'L-Prolin (Kollagen-Baustein)',
    scientificName: 'L-Prolin (1.400 mg aus Yummy Whey)',
    categoryName: 'Aminosäuren & Protein',
    badge: '✨ Kollagen-Tripelhelix & Sehnen',
    summary: 'Essentieller Baustein neben Glycin für die Bildung von Hydroxyprolin und die Stabilität der Kollagen-Dreifachhelix.',
    biochemistry: 'Prolin wird durch die Vitamin-C-abhängige Prolylhydroxylase zu 4-Hydroxyprolin umgewandelt. Hydroxyprolin-Reste bilden intramolekulare Wasserstoffbrückenbindungen aus, die dem Kollagen in Bändern, Sehnen und Knorpel seine extreme Reißfestigkeit verleihen.',
    plantBasedRelevance: 'Mit 30g Yummy Whey nimmst du täglich 1.400 mg reines L-Prolin auf, was im Verbund mit den 4.000 mg Glycin aus CollaSyn® und Vitamin C die körpereigene Kollagenbiosynthese optimal versorgt.',
    intakeAdvice: 'Gemeinsam mit Glycin (CollaSyn®) und Vitamin C morgens oder nach dem Training einnehmen.',
    safetyAndUL: 'Natürliche Proteinkomponente mit uneingeschränkter physiologischer Sicherheit.',
    scientificReference: 'Journal of Biological Chemistry | Matrix Biology | EFSA'
  },
  'whey-protein': {
    id: 'whey-protein',
    name: 'Gesamtprotein (Whey)',
    scientificName: 'Ultrafiltriertes Molkenproteinkonzentrat (23,0 g)',
    categoryName: 'Aminosäuren & Protein',
    badge: '💪 Muskelaufbau & Regeneration',
    summary: 'Höchste biologische Wertigkeit (BW 104) aller Proteinquellen – vollständiges EAA-Profil für Proteinsynthese, Immunsystem und Zellerneuerung.',
    biochemistry: 'Molkenprotein liefert alle 9 essenziellen Aminosäuren in optimalem Verhältnis. Es wird im Magen-Darm-Trakt rasch resorbiert und erzeugt einen schnellen Anstieg der Aminosäurespiegel im Blutplasma (Hyperaminoazidämie), was die muskuläre Proteinsynthese (MPS) via mTORC1 maximal anregt.',
    plantBasedRelevance: 'Bei fleisch- und fischfreier Ernährung sichert das Yummy Whey täglich 23 g hochwertigstes Volleiweiß mit exzellenter Verdaulichkeit und vollständigem Spektrum an essenziellen Aminosäuren ab.',
    intakeAdvice: '30 g Pulver in 200–300 ml Wasser oder Pflanzendrink einrühren, idealerweise direkt nach dem Training oder als proteinreiches Frühstück.',
    safetyAndUL: 'DGE/EFSA Empfehlung für aktive Erwachsene: 1,2–2,0 g Protein pro kg Körpergewicht täglich.',
    scientificReference: 'EFSA Journal 2010;8(10):1811 | Journal of the International Society of Sports Nutrition (JISSN)'
  },
  'bcaa-total': {
    id: 'bcaa-total',
    name: 'BCAAs Gesamt (Leucin, Isoleucin, Valin)',
    scientificName: 'Verzweigtkettige Aminosäuren (5.300 mg)',
    categoryName: 'Aminosäuren & Protein',
    badge: '⚡ Muskelerhalt & Anti-Katabolismus',
    summary: 'Verzweigtkettige Aminosäuren, die die Leberpassage umgehen und direkt im Skelettmuskel verstoffwechselt werden.',
    biochemistry: 'BCAAs machen ca. 35% der essenziellen Aminosäuren im Muskelprotein aus. Sie werden im Skelettmuskel durch die BCAA-Aminotransferase (BCAT) desaminiert und dienen sowohl als direkte Energiesubstrate bei Belastung als auch als molekulare Signale für die Proteinsynthese.',
    plantBasedRelevance: 'Mit 5,3 g BCAA pro Portion liefert das Yummy Whey die exakte physiologische Zieldosis, um Muskelabbau zu verhindern und die Regeneration optimal zu beschleunigen.',
    intakeAdvice: 'Nach dem Training oder am Vormittag zur Unterstützung der täglichen Muskelregeneration.',
    safetyAndUL: 'WHO und EFSA stufen eine Zufuhr von bis zu 20 g BCAA täglich als vollkommen sicher ein.',
    scientificReference: 'American Journal of Physiology | JISSN Position Stand: Protein and Exercise'
  },
  'leucin': {
    id: 'leucin',
    name: 'L-Leucin (BCAA / EAA)',
    scientificName: 'L-Leucin (2.600 mg)',
    categoryName: 'Aminosäuren & Protein',
    badge: '🔑 mTOR-Schalter & Muskelproteinsynthese',
    summary: 'Der stärkste physiologische Anabol-Trigger – aktiviert den mTOR-Komplex zur Initiierung der zellulären Muskelproteinsynthese.',
    biochemistry: 'Leucin bindet intrazellulär an Sestrin2, wodurch die GATOR2-Hemmung aufgehoben und der mTORC1-Proteinkomplex an die Lysosomenmembran rekrutiert wird. Dies phosphoryliert p70S6K und 4E-BP1 und startet die Translation neuer Proteine ("Leucin-Trigger"-Hypothese).',
    plantBasedRelevance: 'Pflanzliche Proteinquellen enthalten oft weniger Leucin (6–8%) als Molkenprotein (11–12%). Die 2.600 mg Leucin aus dem Yummy Whey überschreiten die kritische Reizschwelle von ~2,5 g Leucin pro Mahlzeit ideal.',
    intakeAdvice: 'In der 30 g Shake-Portion enthalten. Ideal mit etwas Kohlenhydraten zur Insulin-Synergie.',
    safetyAndUL: 'Tolerable Upper Intake Level: Bis zu 500 mg/kg Körpergewicht (ca. 35 g/Tag) sind toxikologisch sicher.',
    scientificReference: 'The Journal of Physiology | Cell Metabolism 2016 (Sestrin2-mTORC1 Pathway)'
  },
  'isoleucin': {
    id: 'isoleucin',
    name: 'L-Isoleucin (BCAA / EAA)',
    scientificName: 'L-Isoleucin (1.400 mg)',
    categoryName: 'Aminosäuren & Protein',
    badge: '🔋 Glukoseaufnahme & Hämoglobin',
    summary: 'Fördert die nicht-insulinabhängige Glukoseaufnahme in Muskelzellen und unterstützt die Hämoglobinsynthese.',
    biochemistry: 'Isoleucin stimuliert über PI3K-unabhängige Wege die Translokation von GLUT4-Glukosetransportern in Skelettmuskelzellen und optimiert so die muskuläre Glykogenspeicherung während und nach Belastungen.',
    plantBasedRelevance: 'Essenzielle Aminosäure (WHO-Bedarf ~20 mg/kg). Die 1.400 mg im Shake decken 100% des Tagesbedarfs eigenständig ab.',
    intakeAdvice: 'Bestandteil des natürlichen Molkeproteins.',
    safetyAndUL: 'Sehr hohes Sicherheitsprofil als natürliche Nahrungskomponente.',
    scientificReference: 'Biochemical and Biophysical Research Communications | WHO Technical Report 935'
  },
  'valin': {
    id: 'valin',
    name: 'L-Valin (BCAA / EAA)',
    scientificName: 'L-Valin (1.300 mg)',
    categoryName: 'Aminosäuren & Protein',
    badge: '🧠 Neurotransmitter-Balance & Muskel',
    summary: 'Unterstützt Muskelregeneration, Stickstoffbalance und konkurriert mit Tryptophan um den Transport ins Gehirn gegen zentrale Ermüdung.',
    biochemistry: 'Valin konkurriert am L-Typ-Aminosäuretransporter (LAT1) an der Blut-Hirn-Schranke mit Tryptophan. Dadurch wird ein übermäßiger Tryptophan-Einstrom und vorzeitige Serotonin-vermittelte Ermüdung bei mentaler oder physischer Belastung gedämpft.',
    plantBasedRelevance: 'Essenzielle Aminosäure für Gewebereparatur und kognitive Leistungsfähigkeit.',
    intakeAdvice: 'Bestandteil des täglichen Shakes.',
    safetyAndUL: 'Uneingeschränkt sicher im physiologischen Aminosäureprofil.',
    scientificReference: 'WHO/FAO/UNU Expert Consultation on Protein and Amino Acid Requirements'
  },
  'glutamin': {
    id: 'glutamin',
    name: 'L-Glutamin & Glutaminsäure',
    scientificName: 'L-Glutamin / L-Glutaminsäure (4.100 mg)',
    categoryName: 'Aminosäuren & Protein',
    badge: '🛡️ Darmbarriere (Tight Junctions) & Immunsystem',
    summary: 'Hauptenergielieferant für Darm-Enterozyten und Immunzellen – schützt vor Leaky-Gut und fördert die Erholung.',
    biochemistry: 'Glutamin dient den schnell teilenden Enterozyten des Dünndarms als primäre Energiequelle (Glutaminolyse). Es reguliert die Expression von Claudin-1 und Occludin, wodurch die Tight Junctions der Darmbarriere abgedichtet und mikrobielle Translokationen verhindert werden.',
    plantBasedRelevance: 'Mit 4,1 g Glutamin/Glutaminsäure pro Shake erhält dein Verdauungstrakt maximale Unterstützung für eine intakte Darmmukosa und starke Immunantwort.',
    intakeAdvice: 'Optimal im Protein-Shake nach dem Training oder morgens auf nüchternen Magen.',
    safetyAndUL: 'Studien zeigen selbst bei 20–30 g Glutamin/Tag keinerlei toxische Effekte. 4,1 g ist die perfekte Erhaltungsdosis.',
    scientificReference: 'Lancet | Clinical Nutrition Journal | American Journal of Clinical Nutrition'
  },
  'lysin': {
    id: 'lysin',
    name: 'L-Lysin (EAA)',
    scientificName: 'L-Lysin (2.200 mg)',
    categoryName: 'Aminosäuren & Protein',
    badge: '🧬 Kollagenvernetzung & Carnitin-Präkursor',
    summary: 'Unverzichtbar für die Kollagenvernetzung, Calciumresorption und endogene Synthese von L-Carnitin.',
    biochemistry: 'Lysin wird in Kollagensträngen zu Hydroxylysin modifiziert, welches kovalente Quervernetzungen bildet. Zudem ist Trimethyllysin der biochemische Ausgangsstoff für die körpereigene Biosynthese von L-Carnitin in Leber und Nieren.',
    plantBasedRelevance: 'In vielen Getreidesorten ist Lysin die am stärksten limitierende Aminosäure. Die 2.200 mg im Shake gleichen dieses Profil für Nicht-Fleischesser perfekt aus.',
    intakeAdvice: 'Teil des täglichen Yummy Whey Shakes.',
    safetyAndUL: 'WHO-Referenz (~30 mg/kg = 2.100 mg). Mit 2.200 mg zu 105% optimal versorgt.',
    scientificReference: 'WHO Technical Report Series 935 | Journal of Nutrition'
  },
  'threonin': {
    id: 'threonin',
    name: 'L-Threonin (EAA)',
    scientificName: 'L-Threonin (1.600 mg)',
    categoryName: 'Aminosäuren & Protein',
    badge: '🛡️ Schleimhaut-Mucine & Immunglobuline',
    summary: 'Zentraler Baustein für gastrointestinale Schutzschleime (Mucine), Elastin und Antikörper.',
    biochemistry: 'Bis zu 60% des aufgenommenen Threonins werden im Magen-Darm-Trakt direkt zur Synthese von Mucin-Glykoproteinen genutzt, die die Schleimhaut vor Magensäure, Enzymen und Pathogenen schützen.',
    plantBasedRelevance: 'Essenzielle Aminosäure für gesunde Schleimhäute und Knorpelgewebe.',
    intakeAdvice: 'Bestandteil des täglichen Shakes.',
    safetyAndUL: 'WHO-Referenzwert: 1.050 mg/Tag. Mit 1.600 mg (152%) hervorragend abgedeckt.',
    scientificReference: 'Amino Acids Journal | American Journal of Physiology Gastrointestinal'
  },
  'tryptophan': {
    id: 'tryptophan',
    name: 'L-Tryptophan (EAA)',
    scientificName: 'L-Tryptophan (400 mg)',
    categoryName: 'Aminosäuren & Protein',
    badge: '🌙 Serotonin- & Melatonin-Synthese',
    summary: 'Physiologischer Vorläufer des "Glückshormons" Serotonin und des Schlafhormons Melatonin.',
    biochemistry: 'Tryptophan wird durch die Tryptophan-Hydroxylase (TPH) zu 5-HTP und anschließend zu Serotonin umgewandelt. In der Zirbeldrüse (Epiphyse) entsteht daraus nachts Melatonin zur Steuerung des zirkadianen Rhythmus.',
    plantBasedRelevance: 'Wichtige Aminosäure für Stimmung, Stresstoleranz und Schlafqualität.',
    intakeAdvice: 'Molkenprotein ist von Natur aus besonders reich an bioverfügbarem L-Tryptophan.',
    safetyAndUL: 'WHO-Bedarf (~4 mg/kg = 280 mg). 400 mg (143%) decken den Bedarf vollständig.',
    scientificReference: 'Neuroscience & Biobehavioral Reviews | EFSA Journal'
  },
  'arginin': {
    id: 'arginin',
    name: 'L-Arginin',
    scientificName: 'L-Arginin (600 mg)',
    categoryName: 'Aminosäuren & Protein',
    badge: '🩸 Stickstoffmonoxid (NO) & Gefäßweite',
    summary: 'Einziger Vorläufer für das gefäßerweiternde Signalmolekül Stickstoffmonoxid (NO) und wichtig für den Harnstoffzyklus.',
    biochemistry: 'Die endotheliale Stickstoffmonoxid-Synthase (eNOS) wandelt L-Arginin in NO und L-Citrullin um. NO diffundiert in glatte Gefäßmuskelzellen, aktiviert die Guanylatcyclase und führt zur Gefäßerweiterung (Vasodilation), was Blutdruck und Durchblutung verbessert.',
    plantBasedRelevance: 'Unterstützt die Mikrozirkulation und den ammoniakentgiftenden Harnstoffzyklus der Leber.',
    intakeAdvice: 'Teil des täglichen Yummy Whey Shakes.',
    safetyAndUL: 'Sehr hohes physiologisches Sicherheitsprofil.',
    scientificReference: 'Circulation Research | European Heart Journal'
  },
  'methionin-cystein': {
    id: 'methionin-cystein',
    name: 'Methionin & Cystein (Schwefel-Aminosäuren)',
    scientificName: 'L-Methionin (500 mg) + L-Cystein (500 mg)',
    categoryName: 'Aminosäuren & Protein',
    badge: '🛡️ Glutathion, Keratin & Methylierung',
    summary: 'Schwefelhaltige Aminosäuren für die Glutathion-Synthese, Keratinstruktur (Haare/Nägel) und universelle Methylgruppen (SAMe).',
    biochemistry: 'Methionin wird zu S-Adenosylmethionin (SAMe), dem wichtigsten Methylgruppen-Donator für DNA-Methylierung, Phospholipide und Neurotransmitter. Cystein liefert die Thiolgruppe (-SH) für das intrazelluläre Antioxidans Glutathion.',
    plantBasedRelevance: 'In rein pflanzlichen Hülsenfrüchten oft limitierend; Molkenprotein liefert ein ideales Verhältnis beider Schwefelaminosäuren.',
    intakeAdvice: 'Bestandteil des Yummy Whey Shakes.',
    safetyAndUL: 'WHO-Referenzwert: 1.050 mg/Tag. Mit 1.000 mg (95%) optimal versorgt.',
    scientificReference: 'Journal of Biological Chemistry | Annual Review of Nutrition'
  },
  'laktase': {
    id: 'laktase',
    name: 'Laktase-Enzym',
    scientificName: 'Beta-Galactosidase (30 mg / ~3.000 FCC)',
    categoryName: 'Omega-3 & Vitalstoffe',
    badge: '🥛 Laktose-Spaltung & Bekömmlichkeit',
    summary: 'Verdauungsenzym im Yummy Whey – spaltet Milchzucker (Laktose) zuverlässig auf und verhindert Verdauungsbeschwerden.',
    biochemistry: 'Laktase spaltet das Disaccharid Laktose im Dünndarm enzymatisch in die resorbierbaren Monosaccharide D-Glukose und D-Galaktose. Dadurch wird verhindert, dass ungespaltene Laktose in den Dickdarm gelangt und dort bakteriell zu Gasen fermentiert wird.',
    plantBasedRelevance: 'Sorgt für maximale Magen-Darm-Bekömmlichkeit des Molkenproteins selbst bei leichter Laktosesensitivität.',
    intakeAdvice: 'Bereits im Vit4ever Yummy Whey Pulver enthalten und entfaltet seine Wirkung direkt beim Trinken.',
    safetyAndUL: 'EFSA-geprüftes Verdauungsenzym ohne Obergrenze oder Nebenwirkungen.',
    scientificReference: 'EFSA Journal 2011;9(6):2175 (Health Claim Laktase)'
  },
  'ps': {
    id: 'ps',
    name: 'Phosphatidylserin',
    scientificName: 'Phosphatidylserin (aus Sonnenblumenlecithin) (0 mg - Offen)',
    categoryName: 'Omega-3 & Vitalstoffe',
    badge: '🧠 Kognition & Cortisol-Dämpfung',
    summary: 'Hauptphospholipid der inneren neuronalen Zellmembran – unterstützt Gedächtnis, Signalübertragung und dämpft Stresscortisol.',
    biochemistry: 'Phosphatidylserin aktiviert die neuronale Proteinkinase C (PKC) und Na+/K+-ATPase, moduliert die Freisetzung von Acetylcholin und Dopamin und senkt bei physischem oder mentalem Stress überschießende ACTH- und Cortisolspiegel.',
    plantBasedRelevance: 'In der Nahrung in höchster Dichte in tierischem Hirn- und Organgewebe vorhanden. Pflanzliches Phosphatidylserin (aus Sonnenblumen- oder Sojalecithin) liefert 100-300 mg reines bioverfügbares PS.',
    intakeAdvice: '100-200 mg morgens für kognitiven Fokus oder nach intensivem Training zur Cortisolsenkung.',
    safetyAndUL: 'FDA hat für Phosphatidylserin einen "Qualified Health Claim" für kognitive Gesundheit zuerkannt.',
    scientificReference: 'Nutrition Journal | Journal of the International Society of Sports Nutrition'
  }
};
